import React, { useEffect, useState } from 'react';
import API from '../../utils/api';
import toast from 'react-hot-toast';

const initial = { name: '', websiteUrl: 'https://ugreen.lk/', syncEnabled: false, syncIntervalMinutes: 15, defaultInStockQuantity: 2, safetyStock: 1, maximumSellableStock: '' };
const actionClass = 'px-3 py-2 rounded-lg text-xs font-semibold border border-gray-200 bg-white text-gray-700 hover:bg-gray-50 disabled:opacity-50';

export default function Suppliers() {
  const [rows, setRows] = useState([]); const [form, setForm] = useState(initial); const [busy, setBusy] = useState('');
  const load = () => API.get('/suppliers').then(r => setRows(r.data)).catch(() => toast.error('Failed to load suppliers'));
  useEffect(load, []);
  const save = async e => { e.preventDefault(); if (!form.name || !/^https?:\/\//i.test(form.websiteUrl)) return toast.error('Enter a supplier name and valid HTTP(S) URL'); if (Number(form.syncIntervalMinutes) < 5) return toast.error('Sync interval must be at least 5 minutes'); setBusy('save'); try { await API.post('/suppliers', { ...form, maximumSellableStock: form.maximumSellableStock === '' ? null : Number(form.maximumSellableStock) }); toast.success('Supplier added'); setForm(initial); load(); } catch (e) { toast.error(e.response?.data?.message || 'Could not save supplier'); } finally { setBusy(''); } };
  const act = async (id, action) => { setBusy(`${id}:${action}`); try { const r = await API.post(`/suppliers/${id}/${action}`); toast.success(r.data.message || (action === 'test-connection' ? 'Connection tested' : `${action.replaceAll('-', ' ')} completed`)); load(); } catch (e) { toast.error(e.response?.data?.message || 'Supplier operation failed'); } finally { setBusy(''); } };
  const remove = async id => { if (!window.confirm('Delete this supplier integration? Existing ShopZen products will be preserved, mappings will be paused, and sync logs will remain.')) return; try { await API.delete(`/suppliers/${id}`); toast.success('Supplier integration deleted'); load(); } catch (e) { toast.error(e.response?.data?.message || 'Could not delete supplier integration'); } };
  return <div className="p-4 sm:p-6 max-w-7xl mx-auto">
    <div className="mb-6"><h1 className="text-2xl font-bold text-gray-900">Suppliers</h1><p className="text-sm text-gray-500 mt-1">Safely synchronize supplier availability with ShopZen stock.</p></div>
    <form onSubmit={save} className="bg-white rounded-2xl border border-gray-100 p-4 sm:p-6 mb-6"><h2 className="font-semibold mb-4">Add supplier</h2><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-3">
      <input className="form-input" placeholder="Supplier name" value={form.name} onChange={e => setForm({ ...form, name: e.target.value })}/><input className="form-input" placeholder="Website URL" value={form.websiteUrl} onChange={e => setForm({ ...form, websiteUrl: e.target.value })}/><input className="form-input" type="number" min="5" value={form.syncIntervalMinutes} onChange={e => setForm({ ...form, syncIntervalMinutes: e.target.value })}/><input className="form-input" type="number" min="0" value={form.defaultInStockQuantity} onChange={e => setForm({ ...form, defaultInStockQuantity: e.target.value })}/><input className="form-input" type="number" min="0" value={form.safetyStock} onChange={e => setForm({ ...form, safetyStock: e.target.value })}/><input className="form-input" type="number" min="0" placeholder="Maximum sellable (optional)" value={form.maximumSellableStock} onChange={e => setForm({ ...form, maximumSellableStock: e.target.value })}/><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.syncEnabled} onChange={e => setForm({ ...form, syncEnabled: e.target.checked })}/> Enable automatic sync</label></div><button disabled={busy === 'save'} className="btn-primary mt-4">{busy === 'save' ? 'Saving…' : 'Add Supplier'}</button></form>
    <div className="space-y-4">{rows.length === 0 ? <div className="bg-white rounded-2xl p-8 text-center text-gray-500">No suppliers configured.</div> : rows.map(s => <div key={s._id} className="bg-white rounded-2xl border border-gray-100 p-4 sm:p-6"><div className="flex flex-col gap-4"><div><h2 className="font-semibold text-lg">{s.name}</h2><a className="text-sm text-blue-600 break-all" href={s.websiteUrl} target="_blank" rel="noreferrer">{s.websiteUrl}</a><div className="flex flex-wrap gap-2 mt-2"><span className="px-2 py-1 rounded-full text-xs bg-gray-100">{s.connectionStatus}</span><span className="px-2 py-1 rounded-full text-xs bg-gray-100">{s.platform}</span><span className="px-2 py-1 rounded-full text-xs bg-gray-100">{s.syncEnabled ? 'Auto sync on' : 'Auto sync off'}</span></div><p className="text-xs text-gray-500 mt-2">{s.connectionMessage || 'Not tested'} · {s.discoveredProductCount || 0} discovered · {s.mappedProductCount || 0} mapped</p></div><div className="border-t pt-3"><p className="text-xs font-semibold text-gray-500 mb-2">Supplier actions</p><div className="flex flex-wrap gap-2"><button disabled={!!busy} onClick={() => act(s._id, 'test-connection')} className={actionClass}>1. Test Connection</button><button disabled={!!busy} onClick={() => act(s._id, 'discover-products')} className={actionClass}>2. Discover Products</button><button disabled={!!busy} onClick={() => act(s._id, 'generate-matches')} className={actionClass}>3. Generate Matches</button><button disabled={!!busy} onClick={() => act(s._id, 'sync')} className="px-3 py-2 rounded-lg text-xs font-semibold bg-primary text-white disabled:opacity-50">4. Sync Approved Products</button><button onClick={() => remove(s._id)} className="px-3 py-2 rounded-lg text-xs font-semibold bg-red-50 text-red-700">Delete Integration</button></div><p className="text-xs text-amber-700 mt-2">Products must be discovered and mapped/approved before stock can change.</p></div></div></div>)}</div>
  </div>;
}
